version: "3.7"

services:
  surfing:
    build: ./surfing-back
    container_name: surfing
    image: surfing
    entrypoint: gunicorn app.main:app --config gunicorn.conf.py
    ports:
      - 8000:8000
    volumes:
      - ./surfing-log:/log
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
    depends_on:
      - mariadb
  mariadb:
    container_name: surfing-mariadb
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
  tunnel:
    container_name: surfing-cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file: .env
  portainer-ce:
    container_name: surfing-portainer
    image: portainer/portainer-ce:latest
    restart: always
    expose:
      - "8000"
      - "9000"
      - "9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - /etc/localtime:/etc/localtime:ro 
